apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-argo-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Rajkumar-Aute/nginx-sample.git
    targetRevison: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true