# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger: none
#- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerhub'
        command: 'login'
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerhub'
        repository: '$(DOCKER-REPOSITORY)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: $(Build.BuildId)
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          git config user.email $(EMAIL)
          git config user.name '$(user.name)'
          cat deployment.yaml
          sed -i 's+eks-url.*:${Build.BuildID}+g' deployment.yaml
          cat deployment.yaml
          git add .
          git commit -m 'Done by Azure Pipeline update k8s manifest: ${Build.BuildID}'
          git push --force https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/${GIT_USERNAME}/nginx-sample.git {{branch}}
    